- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.3
  hooks:
  - id: trailing-whitespace
    exclude:
      (?x)(
        ^aiida_siesta/workflows|
        ^aiida_siesta/data|
        ^aiida_siesta/parsers|
        ^aiida_siesta/examples|
        ^aiida_siesta/docs/|
        ^tests/
      )

- repo: local
  hooks:
  - id: prospector
    language: system
    types: [file, python]
    exclude:
     (?x)(
        ^aiida_siesta/workflows|
        ^aiida_siesta/data|
        ^aiida_siesta/parsers|
        ^aiida_siesta/examples|
        ^aiida_siesta/docs/|
        ^tests/
     )
    name: prospector
    description: 'This hook runs Prospector: https://github.com/landscapeio/prospector'
    entry: prospector

