- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.3
  hooks:
  - id: trailing-whitespace
    exclude:
      (?x)(
        ^aiida_siesta/workflows|
        ^aiida_siesta/parsers/stm.py|
        ^aiida_siesta/examples|
        ^aiida_siesta/docs/|
        ^tests/
      )

- repo: local
  hooks:
  - id: yapf
    name: yapf
    entry: yapf
    language: system
    types: [python]
    args: ['-d']
    exclude:
     (?x)(
        ^aiida_siesta/calculations/stm.py|
        ^aiida_siesta/workflows|
        ^aiida_siesta/parsers/stm.py|
        ^aiida_siesta/examples|
        ^aiida_siesta/docs/|
        ^tests/
     )
  - id: prospector
    language: system
    types: [file, python]
    exclude:
     (?x)(
        ^aiida_siesta/calculations/stm.py|
        ^aiida_siesta/workflows|
        ^aiida_siesta/parsers/stm.py|
        ^aiida_siesta/parsers/json_time.py|
        ^aiida_siesta/examples|
        ^aiida_siesta/docs/|
        ^tests/
     )
    name: prospector
    description: 'This hook runs Prospector: https://github.com/landscapeio/prospector'
    entry: prospector

