version: "3"

services:
  aiida:
    image: aiida_siesta_code:0.10.1
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - /code/siesta_plugin/dockerscripts/setup_develop.sh
    depends_on:
      - db
    volumes:
      - ./:/code/siesta_plugin/

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER:     aiida
      POSTGRES_PASSWORD: aiidapwd
      POSTGRES_DB:       aiidadb
    ports:
        - 5432:5432
    deploy:
      restart_policy:
        condition: on-failure
