version: "3"

services:
  aiida:
    image: aiida_siesta_dev:latest
    deploy:
      restart_policy:
        condition: on-failure
    command: /bin/bash /code/scripts/docker-start.sh
    depends_on:
      - db
    volumes:
      - ./docker-start.sh:/code/scripts/docker-start.sh
      - ./test.sh:/code/test.sh
      # - aiidalogs:/root/.aiida/
      # - aiidarepo:/root/.aiida-repo/

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER:     aiida
      POSTGRES_PASSWORD: aiidapwd
      POSTGRES_DB:       aiidadb
    # volumes:
      # - pgdata:/var/lib/postgresql/data
    ports:
        - 5432:5432
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  pgdata:
    driver: local
  aiidalogs:
    driver: local
  aiidarepo:
    driver: local
